export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const ACCEPT_REQUEST = 'ACCEPT_REQUEST';
export const ACCEPTED_REQUEST = 'ACCEPTED_REQUEST';
export const RECEIVE_REQUEST = 'RECEIVE_REQUEST';
export const SEND_REQUEST = 'SEND_REQUEST';
